README.md, test/LiveServer.hs
Enable via setting MINIO_LOCAL environment variable during tests.
=> Add support to run tests against a locally running minio server

src/Network/Minio.hs, src/Network/Minio/PutObject.hs
This change makes copyObject use multipart strategy when the object to
be created has a size larger than 64 MiB. Previously this strategy was
used when the object is larger than 5GiB only.
=> Use multipart copy in copyObject smaller files:

src/Network/Minio/Data.hs, src/Network/Minio/ListOps.hs, src/Network/Minio/S3API.hs, test/LiveServer.hs
also take max-uploads as an argument for listIncompleteUploads' and max-keys for listObjects'
Fixes #47 
Fixes #46
=> Export ListUploadsResult and ListObjectsResult

test/LiveServer.hs
Minio server changed behaviour to return no incomplete uploads. This
change is to make tests pass against the new server behaviour.
=> Fix live-server test relating to incomplete uploads

examples/FileUploader.hs, minio-hs.cabal, src/Network/Minio/Utils.hs, test/Network/Minio/Utils/Test.hs, test/Spec.hs
Also simplifies implementation using lifted `bracket_` and async
routines, instead of lifted control operations like `liftBaseOp_`
=> Fix concurrency bug in `limitedMapConcurrently`

docs/API.md, examples/PresignedGetObject.hs, examples/PresignedPutObject.hs, examples/PutObject.hs, src/Network/Minio.hs, src/Network/Minio/PresignedOperations.hs, test/LiveServer.hs
- Add full examples for presignedGetObjectUrl and
presignedPutObjectUrl
- Lower-case `*URL` API functions to `*Url` to adopt a Haskell naming
convention
Finishes and fixes #35, #36 and #37.
=> Add documentation for presigned operations

minio-hs.cabal
This should allow building the library with GHC 8.2.1 on Stackage
nightly.
=> Remove upper bound on protolude version

docs/API.md, examples/CopyObject.hs, minio-hs.cabal, src/Network/Minio.hs, src/Network/Minio/CopyObject.hs, src/Network/Minio/Data.hs, src/Network/Minio/PutObject.hs, src/Network/Minio/S3API.hs, src/Network/Minio/Utils.hs, test/LiveServer.hs, test/Spec.hs
* Allows adding additional record members to SourceInfo and DestinationInfo without breaking
applications (e.g, encryption related options).
* Move high-level copyObject functions to CopyObject module
=> Make copyObject use SourceInfo, DestinationInfo

src/Network/Minio/PutObject.hs, src/Network/Minio/S3API.hs, test/LiveServer.hs
Current functionality only supported stream based
uploads using multipart, this meant that even for
small file sizes we were performing multipart operations
which is slower and unnecessary.
This PR fixes this behavior.
=> api: Support single PUT on stream uploads

minio-hs.cabal, src/Network/Minio.hs, src/Network/Minio/Data.hs, src/Network/Minio/S3API.hs, src/Network/Minio/XmlGenerator.hs, src/Network/Minio/XmlParser.hs, test/Network/Minio/TestHelpers.hs, test/Network/Minio/Utils/Test.hs, test/Network/Minio/XmlGenerator/Test.hs, test/Network/Minio/XmlParser/Test.hs
While GCS is S3 v4 compatible, it uses a different xml namespace url
than AWS (and Minio).
=> Infer XML namespace using connectHost 

src/Network/Minio/Data.hs
We use "us", a Multi-Regional location by default.
=> Fix connectRegion for gcsCI

minio-hs.cabal, src/Network/Minio.hs, src/Network/Minio/API.hs, src/Network/Minio/CopyObject.hs, src/Network/Minio/Data.hs, src/Network/Minio/Errors.hs, src/Network/Minio/S3API.hs, src/Network/Minio/Sign/V4.hs, test/LiveServer.hs, test/Network/Minio/XmlGenerator/Test.hs, test/Network/Minio/XmlParser/Test.hs
- Remove ConnectInfo's Default instance
- Add support for reading from well-known credential files and
environment variables
- should we move `minioPlayCI`, `awsCI` etc to use `connectInfo` / `connectInfoWithCreds`?
- should we make then `IO ConnectInfo` as opposed to pure values?
##TODO
=> improve initializing ConnectInfo

examples/BucketExists.hs, minio-hs.cabal, src/Network/Minio.hs, src/Network/Minio/Data.hs
- Check if ConnectInfo is secure
- Option to disable TLS certificate validation (to make testing
easier).
=> Add simple TLS helpers:

minio-hs.cabal, src/Network/Minio/API.hs, src/Network/Minio/APICommon.hs, src/Network/Minio/Data.hs, src/Network/Minio/Errors.hs, src/Network/Minio/PutObject.hs, src/Network/Minio/S3API.hs, src/Network/Minio/Sign/V4.hs, src/Network/Minio/Utils.hs
Use streaming signature to avoid reading the body twice in PutObject
requests, where the body can be upto 5GIB.
Note that the body is signed only used when the connection is not
using TLS.
=> Add streaming signature for PutObject

src/Network/Minio/Data.hs
I noticed that us-west-2 wasn't working for me, which then lead me to find that us-west-2 wasn't included in the `Data` module.
=> correct us-west-2 region reference in minio data module

.travis.yml, CHANGELOG.md, README.md, examples/BucketExists.hs, examples/CopyObject.hs, examples/FileUploader.hs, examples/GetConfig.hs, examples/GetObject.hs, examples/HeadObject.hs, examples/Heal.hs, examples/ListBuckets.hs, examples/ListIncompleteUploads.hs, examples/ListObjects.hs, examples/MakeBucket.hs, examples/PresignedGetObject.hs, examples/PresignedPostPolicy.hs, examples/PresignedPutObject.hs, examples/PutObject.hs, examples/README.md, examples/RemoveBucket.hs, examples/RemoveIncompleteUpload.hs, examples/RemoveObject.hs, examples/SelectObject.hs, examples/ServerInfo.hs, examples/ServiceSendRestart.hs, examples/ServiceSendStop.hs, examples/ServiceStatus.hs, examples/SetConfig.hs, minio-hs.cabal
- Disable building live-server tests by default; build only in CI
- Update examples and README
- Build examples in CI via new opt-in cabal flag
- Drop GHC 8.2.2 support
- Update version for new release
=> New release

src/Network/Minio/Data.hs, src/Network/Minio/XmlGenerator.hs, test/Network/Minio/XmlGenerator/Test.hs
- Test was failing because of non-unique ordering of CSV properties. It is fixed
by sorting the CSV properties before serialization.
=> Fix XML generation test for S3 SELECT

minio-hs.cabal, src/Network/Minio/API.hs, src/Network/Minio/APICommon.hs, src/Network/Minio/Data.hs, src/Network/Minio/Data/Time.hs, src/Network/Minio/PresignedOperations.hs, src/Network/Minio/Sign/V4.hs, test/LiveServer.hs
- Also update standard S3 endpoints
- Unify code that determines if path style or virtual style must be used for
regular and presigned requests
=> Use region specific endpoints for AWS S3 in presigned Urls

.github/workflows/ci.yml, examples/FileUploader.hs, minio-hs.cabal, src/Lib/Prelude.hs, src/Network/Minio.hs, src/Network/Minio/APICommon.hs, src/Network/Minio/AdminAPI.hs, src/Network/Minio/CopyObject.hs, src/Network/Minio/Data.hs, src/Network/Minio/Data/ByteString.hs, src/Network/Minio/Data/Crypto.hs, src/Network/Minio/Errors.hs, src/Network/Minio/JsonParser.hs, src/Network/Minio/ListOps.hs, src/Network/Minio/PresignedOperations.hs, src/Network/Minio/PutObject.hs, src/Network/Minio/S3API.hs, src/Network/Minio/SelectAPI.hs, src/Network/Minio/Sign/V4.hs, src/Network/Minio/Utils.hs, src/Network/Minio/XmlGenerator.hs, src/Network/Minio/XmlParser.hs, stack.yaml, stack.yaml.lock, test/LiveServer.hs, test/Network/Minio/API/Test.hs, test/Network/Minio/TestHelpers.hs, test/Network/Minio/Utils/Test.hs, test/Spec.hs
- relude is a better and more commonly used library
- Add compiler warnings and fixes
- Update stack lts to 18.24
- Add explicit deriving strategies
=> Replace protolude with relude and build with GHC 9.0.2

minio-hs.cabal, src/Network/Minio/PresignedOperations.hs, stack.yaml, stack.yaml.lock
This PR adds support for Aeson 2, which became standard on Stackage resolvers in early February 2022.
Please let me know if you'd like me to update `ci.yml` also. I think it would make the most sense to add `9.0.2` and/or `9.2.2` to the "stack" matrix, since then it should be guaranteed to build against Aeson 2.
=> Support Aeson 2

.github/workflows/ci.yml, README.md, minio-hs.cabal
This turns on the GHC option `-Werror` to ensure that warnings fail the build in dev mode. The flag is enabled in the CI.
README is updated with cabal based instructions.
=> Add `dev` flag to cabal file and update README

.github/workflows/ci.yml, examples/AssumeRole.hs, minio-hs.cabal, src/Network/Minio/API.hs, src/Network/Minio/AdminAPI.hs, src/Network/Minio/Credentials.hs, src/Network/Minio/Data.hs, src/Network/Minio/PresignedOperations.hs, src/Network/Minio/Sign/V4.hs, src/Network/Minio/XmlParser.hs, test/LiveServer.hs
This exports a new module for retrieving STS based credentials, however they are not yet convenient to use in the library - the session token needs to be included as a custom header and may not be possible with all APIs.
=> Add Credentials module to use Assume Role API

CHANGELOG.md, README.md, examples/AssumeRole.hs, minio-hs.cabal, src/Network/Minio.hs, src/Network/Minio/API.hs, src/Network/Minio/AdminAPI.hs, src/Network/Minio/Credentials.hs, src/Network/Minio/Credentials/AssumeRole.hs, src/Network/Minio/Credentials/Types.hs, src/Network/Minio/Data.hs, src/Network/Minio/Errors.hs, src/Network/Minio/PresignedOperations.hs, src/Network/Minio/S3API.hs, src/Network/Minio/Sign/V4.hs, src/Network/Minio/Utils.hs, src/Network/Minio/XmlCommon.hs, src/Network/Minio/XmlGenerator.hs, src/Network/Minio/XmlParser.hs, test/LiveServer.hs, test/Spec.hs
This change adds support for requesting temporary object storage credentials using the STS API. Some breaking changes are introduced to enable this support:
- `Credentials` type has been removed. Use the `CredentialValue` type instead. Corresponding to this the type signature for `setCreds` has changed, though the functionality is the same.
- The type alias `Provider` has been renamed to `CredentialLoader` to avoid naming confusion.
=> Add support for AssumeRole STS API

.github/workflows/ci.yml, minio-hs.cabal, src/Lib/Prelude.hs, src/Network/Minio/API.hs, src/Network/Minio/Credentials.hs, src/Network/Minio/Credentials/AssumeRole.hs, src/Network/Minio/Credentials/Types.hs, src/Network/Minio/Data.hs, src/Network/Minio/Data/Crypto.hs, src/Network/Minio/SelectAPI.hs, src/Network/Minio/Sign/V4.hs, src/Network/Minio/Utils.hs, src/Network/Minio/XmlCommon.hs, src/Network/Minio/XmlParser.hs, test/LiveServer.hs
- Types defined in Credentials.Types and Network.Minio.Data are now strict
=> Enable StrictData and bump up version for release

minio-hs.cabal
The connection package is not maintained anymore and doesn't work with GHC 9.6
I've found the crypton-connection fork via https://discourse.haskell.org/t/fork-of-archived-connection-a-k-a-hs-connection-library/8545
=> Use crypton-connection instead of connection

.github/workflows/ci.yml, minio-hs.cabal, stack.yaml, stack.yaml.lock, test/LiveServer.hs
Tests needing fixing for recent minio
Also:
- set minimum tested version to 8.10
- remove building with cabal 3.6
- update stack.yaml to add crypton-connection
Update live server test env var handling
=> Add GHC 9.6 to CI

minio-hs.cabal, src/Network/Minio/Data.hs
crypton-connection versions >= 0.4.0 [added a new field](https://github.com/kazu-yamamoto/crypton-connection/pull/3) to `TLSConnectionSettings`. This broke some code in `minio-hs` that didn't supply the new field. This PR addresses that by using the `def` value for `TLSSettings` which is the same as the one that minio-hs was creating except for one pre-existing field. By using `def` the code should remain compatible with `crypton-connection` versions < 0.4.0 too.
=> Compatibility with crypton-connection >= 0.4.0

src/Network/Minio/Utils.hs
As per [the HTTP Spec](https://www.rfc-editor.org/rfc/rfc9110.html#section-9.3.2) server responses to HEAD Requests must not contain bodies.
Nontheless `minio-hs` relies on the existence of a `Content-Type` header as a heuristic of whether to expect an error message in the body of the response.  
Some S3 api servers (such as [garage](https://git.deuxfleurs.fr/Deuxfleurs/garage)) adhere to the http spec and produce responses to HEAD requests without bodies but containing a `Content-Type` header (because an analogous `GET` request would return one).
`minio-hs` currently fails in such situations.
=> Ignore Body of Responses to HEAD Requests as per Spec
