minio-hs.cabal, src/Lib/Prelude.hs, src/Network/Minio.hs, src/Network/Minio/Data.hs, src/Network/Minio/Errors.hs, src/Network/Minio/PutObject.hs, src/Network/Minio/S3API.hs, src/Network/Minio/Utils.hs, src/Network/Minio/XmlParser.hs, test/LiveServer.hs, test/Network/Minio/XmlParser/Test.hs, test/Spec.hs
=> Copyobject

test/LiveServer.hs
This is for the live-server tests - as higher number of parallel tests with the play servers is leading lots of build failures.
=> Refactor tests to group into fewer parallel tests

docs/API.md, examples/listIncompleteUploads.hs, src/Network/Minio.hs, src/Network/Minio/Data.hs, src/Network/Minio/ListOps.hs, src/Network/Minio/XmlParser.hs, test/LiveServer.hs, test/Network/Minio/XmlParser/Test.hs
=> listIncompleteUploads returns upload size like other SDKs

docs/API.md, src/Network/Minio.hs, src/Network/Minio/Data.hs
* Introduce ConnectInfo and its smart constructors
* Introduce the Minio monad and provide a simple example
=> Clean up ConnectInfo smart constructors + doc sections:

docs/API.md, examples/RemoveObject.hs, src/Network/Minio.hs, test/LiveServer.hs
* Add an example
* Fix minor issues in API.md
Fixes #13
=> Add removeObject function

examples/GetObject.hs, src/Network/Minio/API.hs, src/Network/Minio/Errors.hs, src/Network/Minio/Sign/V4.hs
Also fixed issue in fetching endpoint corresponding to region for AWS S3.
=> Add port to host header for signing.

examples/CopyObject.hs, src/Network/Minio/Utils.hs, test/LiveServer.hs
=> Add copyObject example.

README.md, docs/API.md, examples/BucketExists.hs, examples/CopyObject.hs, examples/FileUploader.hs, examples/GetObject.hs, examples/HeadObject.hs, examples/ListBuckets.hs, examples/ListIncompleteUploads.hs, examples/ListObjects.hs, examples/Makebucket.hs, examples/RemoveObject.hs, examples/Removebucket.hs, src/Network/Minio.hs, src/Network/Minio/S3API.hs, test/LiveServer.hs
Also fixed examples to work with lts-8.5
Fixes #26
=> Add isBucketExists and headBucket APIs

README.md, docs/API.md, examples/BucketExists.hs, examples/CopyObject.hs, examples/FileUploader.hs, examples/GetObject.hs, examples/HeadObject.hs, examples/ListBuckets.hs, examples/ListIncompleteUploads.hs, examples/ListObjects.hs, examples/Makebucket.hs, examples/PutObject.hs, examples/RemoveObject.hs, examples/Removebucket.hs, src/Network/Minio.hs, src/Network/Minio/Data.hs, test/LiveServer.hs
This reduces one thing that the library user needs to know.
=> Move runResourceT into Minio monad

CHANGELOG.md, README.md, minio-hs.cabal, stack.yaml
* Switch to Stackage LTS 9.1
* Minor update to description in cabal file
* Add Slack badge and update Hackage badge in README.md
=> Bump up version for new release 0.3.1

docs/API.md, examples/RemoveIncompleteUpload.hs, src/Network/Minio.hs, test/LiveServer.hs
=> Add removeIncompleteupload API

minio-hs.cabal, src/Lib/Prelude.hs, src/Network/Minio.hs, src/Network/Minio/API.hs, src/Network/Minio/Data.hs, src/Network/Minio/Errors.hs, src/Network/Minio/S3API.hs, src/Network/Minio/Sign/V4.hs, src/Network/Minio/Utils.hs, test/LiveServer.hs
Additionally, refactors signing code for readability and the ability
to reuse for pre-signing.
=> Add presigned operations APIs

docs/API.md, src/Network/Minio.hs, src/Network/Minio/Data.hs, src/Network/Minio/ListOps.hs, src/Network/Minio/S3API.hs, src/Network/Minio/XmlParser.hs, test/LiveServer.hs, test/Network/Minio/XmlParser/Test.hs
This is added for legacy requirements
=> Add ListObjectsV1 API support

src/Network/Minio.hs, src/Network/Minio/Data.hs, src/Network/Minio/S3API.hs, src/Network/Minio/XmlGenerator.hs, src/Network/Minio/XmlParser.hs, test/Network/Minio/XmlGenerator/Test.hs, test/Network/Minio/XmlParser/Test.hs
~TODO: A live server test, but needs some thinking as notification depends on some server side config for Minio.~
Will not be adding a live-server test as all notification configuration requires server-side configuration too.
Instead a later PR will add full examples for notification APIs.
=> Add Bucket Notification APIs

src/Network/Minio.hs, src/Network/Minio/S3API.hs, test/LiveServer.hs
=> Implement getBucketPolicy/setBucketPolicy

minio-hs.cabal, src/Network/Minio/API.hs, src/Network/Minio/APICommon.hs, src/Network/Minio/AdminAPI.hs, src/Network/Minio/Data.hs, src/Network/Minio/Errors.hs, test/Network/Minio/API/Test.hs, test/Spec.hs
- Add Admin API helper functions like buildAdminRequest
=> Add getServerInfo admin API

examples/GetConfig.hs, examples/SetConfig.hs, minio-hs.cabal, src/Network/Minio/AdminAPI.hs, src/Network/Minio/JsonParser.hs, src/Network/Minio/Utils.hs, test/Network/Minio/JsonParser/Test.hs
=> Add setConfig/getConfig API

src/Network/Minio/PresignedOperations.hs, test/LiveServer.hs
- Also split out live server tests into individual functions
=> Fix region setting in presigned url functions

src/Network/Minio.hs, src/Network/Minio/Data.hs, src/Network/Minio/Data/Crypto.hs, src/Network/Minio/Errors.hs, test/LiveServer.hs, test/Spec.hs
Needs a major version bump as we end up removing Eq and Show instance on PutObjectOptions
=> Add encryption options to GetObjectOptions and PutObjectOptions

minio-hs.cabal, src/Network/Minio/API.hs
=> Retry requests that timeout using full-jitter backoff

src/Network/Minio.hs, src/Network/Minio/Data.hs
... to allow applications to manage application resources along side
MinIO SDK's internal resources
This PR is inspired by #124.
=> Expose runMinioRes/runMinioResWith

CHANGELOG.md, src/Network/Minio.hs, src/Network/Minio/Data.hs, src/Network/Minio/S3API.hs, test/LiveServer.hs
This allows retrieving the ObjectInfo of an object during the
getObject call.
=> Add GetObjectResponse data type

.github/workflows/ci.yml
=> Test GHC 9.0.2 and 9.2.2 with Stack

.github/workflows/ci.yml, examples/PresignedGetObject.hs, examples/PresignedPutObject.hs, src/Network/Minio/AdminAPI.hs, src/Network/Minio/CopyObject.hs, src/Network/Minio/Data.hs, src/Network/Minio/ListOps.hs, src/Network/Minio/PresignedOperations.hs, src/Network/Minio/S3API.hs, src/Network/Minio/Sign/V4.hs, src/Network/Minio/XmlGenerator.hs, src/Network/Minio/XmlParser.hs, test/LiveServer.hs, test/Spec.hs
=> Update with changes for ormolu 0.5.0.0

examples/FileUploader.hs, examples/GetConfig.hs, examples/GetObject.hs, examples/Heal.hs, examples/ListIncompleteUploads.hs, examples/ListObjects.hs, examples/PresignedGetObject.hs, examples/PresignedPostPolicy.hs, examples/SelectObject.hs, examples/ServerInfo.hs, examples/ServiceSendRestart.hs, examples/ServiceSendStop.hs, examples/ServiceStatus.hs, minio-hs.cabal, src/Network/Minio/API.hs, src/Network/Minio/AdminAPI.hs, src/Network/Minio/Data.hs, src/Network/Minio/ListOps.hs, src/Network/Minio/PresignedOperations.hs, src/Network/Minio/S3API.hs, src/Network/Minio/Sign/V4.hs, src/Network/Minio/Utils.hs, src/Network/Minio/XmlGenerator.hs, src/Network/Minio/XmlParser.hs, test/LiveServer.hs, test/Network/Minio/JsonParser/Test.hs, test/Network/Minio/XmlParser/Test.hs, test/Spec.hs
- Will require major version bump as some types were changed from data
to newtype
=> Hlint fixes
